services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: production
    volumes:
      - ./client/src/generated/api:/app/src/generated/api
    depends_on:
      server:
        condition: service_healthy
    ports:
      - "3000:3000"
    env_file:
      - .env.dev
    networks:
      - dokploy-network
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.client-app.rule=Host(`app.rsp.org.au`)
      - traefik.http.routers.client-app.entrypoints=web
      - traefik.http.services.client-app.loadbalancer.server.port=3000

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: production
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "4000:4000"
    env_file:
      - .env.dev
    networks:
      - dokploy-network
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.server-app.rule=Host(`server.rsp.org.au`)
      - traefik.http.routers.server-app.entrypoints=web
      - traefik.http.services.server-app.loadbalancer.server.port=3000

  postgres:
    image: postgres:17.5-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./logs/postgres:/var/log/postgresql
    networks:
      - dokploy-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  dokploy-network:
    external: true

volumes:
  postgres_data:
    driver: local
  grafana_data:
    driver: local
