services:
  server:
    ports:
      - "4000:4000"
    env_file:
      - .env.dev
    volumes:
      - ./server:/app/src
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 10s
      timeout: 5s
      retries: 10

  postgres:
    ports:
      - "5432:5432"
    env_file:
      - .env.dev

  client:
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    env_file:
      - .env.dev
    depends_on:
      server:
        condition: service_healthy

  prometheus:
      depends_on:
        server:
          condition: service_healthy

  grafana:
    ports:
      - "8000:3000"
    env_file:
      - .env.dev
    depends_on:
      server:
        condition: service_healthy
