services:
  server:
    ports:
      - "4000:4000"
    env_file:
      - .env.dev

  postgres:
    ports:
      - "5432:5432"
    env_file:
      - .env.dev
  
  client:
    env_file:
      - .env.dev
