// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RSPWebAPI.Database;

#nullable disable

namespace RSPWebAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241020003910_ProblemAttempts")]
    partial class ProblemAttempts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LeetcodeProblemLeetcodeProblemCategory", b =>
                {
                    b.Property<Guid>("LeetcodeProblemCategoriesLeetcodeProblemCategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LeetcodeProblemsLeetcodeProblemId")
                        .HasColumnType("uuid");

                    b.HasKey("LeetcodeProblemCategoriesLeetcodeProblemCategoryId", "LeetcodeProblemsLeetcodeProblemId");

                    b.HasIndex("LeetcodeProblemsLeetcodeProblemId");

                    b.ToTable("LeetcodeProblemLeetcodeProblemCategory");
                });

            modelBuilder.Entity("RSPWebAPI.Entities.CustomProblem", b =>
                {
                    b.Property<Guid>("CustomProblemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CustomProblemId");

                    b.HasIndex("ProblemId");

                    b.ToTable("CustomProblems");
                });

            modelBuilder.Entity("RSPWebAPI.Entities.Enrollment", b =>
                {
                    b.Property<Guid>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("RoleId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("UserId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("RSPWebAPI.Entities.LeetcodeProblem", b =>
                {
                    b.Property<Guid>("LeetcodeProblemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LeetcodeProblemDifficultyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid");

                    b.HasKey("LeetcodeProblemId");

                    b.HasIndex("LeetcodeProblemDifficultyId");

                    b.HasIndex("ProblemId");

                    b.ToTable("LeetcodeProblems");
                });

            modelBuilder.Entity("RSPWebAPI.Entities.LeetcodeProblemCategory", b =>
                {
                    b.Property<Guid>("LeetcodeProblemCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ProblemId")
                        .HasColumnType("uuid");

                    b.HasKey("LeetcodeProblemCategoryId");

                    b.HasIndex("ProblemId");

                    b.ToTable("LeetcodeProblemCategories");
                });

            modelBuilder.Entity("RSPWebAPI.Entities.LeetcodeProblemDifficulty", b =>
                {
                    b.Property<Guid>("LeetcodeProblemDifficultyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LeetcodeProblemDifficultyId");

                    b.ToTable("LeetcodeProblemDifficulties");
                });

            modelBuilder.Entity("RSPWebAPI.Entities.Mentorship", b =>
                {
                    b.Property<Guid>("MentorshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MenteeEnrollmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MentorEnrollmentId")
                        .HasColumnType("uuid");

                    b.HasKey("MentorshipId");

                    b.HasIndex("MenteeEnrollmentId");

                    b.HasIndex("MentorEnrollmentId");

                    b.ToTable("Mentorships");
                });

            modelBuilder.Entity("RSPWebAPI.Entities.Problem", b =>
                {
                    b.Property<Guid>("ProblemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProblemId");

                    b.ToTable("Problems");
                });

            modelBuilder.Entity("RSPWebAPI.Entities.ProblemAttempt", b =>
                {
                    b.Property<Guid>("ProblemAttemptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AttemptStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CustomProblemId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EnrollmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LeetcodeProblemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TimeTakenInMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("ProblemAttemptId");

                    b.HasIndex("CustomProblemId");

                    b.HasIndex("EnrollmentId");

                    b.HasIndex("LeetcodeProblemId");

                    b.HasIndex("UserId");

                    b.ToTable("ProblemAttempts");
                });

            modelBuilder.Entity("RSPWebAPI.Entities.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("RSPWebAPI.Entities.Season", b =>
                {
                    b.Property<Guid>("SeasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SeasonId");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("RSPWebAPI.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DiscordId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfileImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LeetcodeProblemLeetcodeProblemCategory", b =>
                {
                    b.HasOne("RSPWebAPI.Entities.LeetcodeProblemCategory", null)
                        .WithMany()
                        .HasForeignKey("LeetcodeProblemCategoriesLeetcodeProblemCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RSPWebAPI.Entities.LeetcodeProblem", null)
                        .WithMany()
                        .HasForeignKey("LeetcodeProblemsLeetcodeProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RSPWebAPI.Entities.CustomProblem", b =>
                {
                    b.HasOne("RSPWebAPI.Entities.Problem", "Problem")
                        .WithMany()
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("RSPWebAPI.Entities.Enrollment", b =>
                {
                    b.HasOne("RSPWebAPI.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RSPWebAPI.Entities.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RSPWebAPI.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Season");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RSPWebAPI.Entities.LeetcodeProblem", b =>
                {
                    b.HasOne("RSPWebAPI.Entities.LeetcodeProblemDifficulty", "LeetcodeProblemDifficulty")
                        .WithMany()
                        .HasForeignKey("LeetcodeProblemDifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RSPWebAPI.Entities.Problem", "Problem")
                        .WithMany()
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeetcodeProblemDifficulty");

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("RSPWebAPI.Entities.LeetcodeProblemCategory", b =>
                {
                    b.HasOne("RSPWebAPI.Entities.Problem", null)
                        .WithMany("LeetcodeProblemCategories")
                        .HasForeignKey("ProblemId");
                });

            modelBuilder.Entity("RSPWebAPI.Entities.Mentorship", b =>
                {
                    b.HasOne("RSPWebAPI.Entities.Enrollment", "MenteeEnrollment")
                        .WithMany()
                        .HasForeignKey("MenteeEnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RSPWebAPI.Entities.Enrollment", "MentorEnrollment")
                        .WithMany()
                        .HasForeignKey("MentorEnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenteeEnrollment");

                    b.Navigation("MentorEnrollment");
                });

            modelBuilder.Entity("RSPWebAPI.Entities.ProblemAttempt", b =>
                {
                    b.HasOne("RSPWebAPI.Entities.CustomProblem", "CustomProblem")
                        .WithMany()
                        .HasForeignKey("CustomProblemId");

                    b.HasOne("RSPWebAPI.Entities.Enrollment", "Enrollment")
                        .WithMany()
                        .HasForeignKey("EnrollmentId");

                    b.HasOne("RSPWebAPI.Entities.LeetcodeProblem", "LeetcodeProblem")
                        .WithMany()
                        .HasForeignKey("LeetcodeProblemId");

                    b.HasOne("RSPWebAPI.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomProblem");

                    b.Navigation("Enrollment");

                    b.Navigation("LeetcodeProblem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RSPWebAPI.Entities.Problem", b =>
                {
                    b.Navigation("LeetcodeProblemCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
