// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RSPWebAPI.Database;

#nullable disable

namespace RSPWebAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251029120704_AddKickStudentEvent")]
    partial class AddKickStudentEvent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LeetcodeProblemCategoryEntityLeetcodeProblemEntity", b =>
                {
                    b.Property<string>("LeetcodeProblemCategoriesLeetcodeProblemCategoryId")
                        .HasColumnType("varchar(16)");

                    b.Property<string>("LeetcodeProblemEntityLeetcodeProblemId")
                        .HasColumnType("varchar(16)");

                    b.HasKey("LeetcodeProblemCategoriesLeetcodeProblemCategoryId", "LeetcodeProblemEntityLeetcodeProblemId");

                    b.HasIndex("LeetcodeProblemEntityLeetcodeProblemId");

                    b.ToTable("LeetcodeProblemCategoryMapping", (string)null);
                });

            modelBuilder.Entity("RSPWebAPI.Entities.BehaviouralMockInterviewRoundEntity", b =>
                {
                    b.Property<string>("BehaviouralMockInterviewRoundId")
                        .HasColumnType("varchar(16)")
                        .HasColumnName("BehaviouralMockInterviewRoundId");

                    b.Property<int>("BehavioralScore")
                        .HasColumnType("int")
                        .HasColumnName("BehavioralScore");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("DeletedAtUtc");

                    b.HasKey("BehaviouralMockInterviewRoundId");

                    b.ToTable("BehaviouralMockInterviewRound", (string)null);
                });

            modelBuilder.Entity("RSPWebAPI.Entities.CustomMockInterviewRoundEntity", b =>
                {
                    b.Property<string>("CustomMockInterviewRoundId")
                        .HasColumnType("varchar(16)")
                        .HasColumnName("CustomMockInterviewRoundId");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("varchar(10000)")
                        .HasColumnName("Content");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("DeletedAtUtc");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Link");

                    b.Property<int>("Score")
                        .HasColumnType("int")
                        .HasColumnName("Score");

                    b.HasKey("CustomMockInterviewRoundId");

                    b.ToTable("CustomMockInterviewRound", (string)null);
                });

            modelBuilder.Entity("RSPWebAPI.Entities.CustomProblemEntity", b =>
                {
                    b.Property<string>("CustomProblemId")
                        .HasColumnType("varchar(16)")
                        .HasColumnName("CustomProblemId");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("DeletedAtUtc");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Difficulty");

                    b.Property<string>("ProblemId")
                        .IsRequired()
                        .HasColumnType("varchar(16)")
                        .HasColumnName("ProblemId");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Question");

                    b.HasKey("CustomProblemId");

                    b.HasIndex("ProblemId")
                        .IsUnique();

                    b.ToTable("CustomProblem", (string)null);
                });

            modelBuilder.Entity("RSPWebAPI.Entities.EnrollmentEntity", b =>
                {
                    b.Property<string>("EnrollmentId")
                        .HasColumnType("varchar(16)")
                        .HasColumnName("EnrollmentId");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("DeletedAtUtc");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("Role");

                    b.Property<string>("SeasonId")
                        .IsRequired()
                        .HasColumnType("varchar(16)")
                        .HasColumnName("SeasonId");

                    b.Property<int>("StudentRolePromotion")
                        .HasColumnType("int")
                        .HasColumnName("StudentRolePromotion");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(16)")
                        .HasColumnName("UserId");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("UserId");

                    b.HasIndex("SeasonId", "UserId");

                    b.ToTable("Enrollment", (string)null);
                });

            modelBuilder.Entity("RSPWebAPI.Entities.KickStudentEventEntity", b =>
                {
                    b.Property<string>("KickStudentEventId")
                        .HasColumnType("varchar(16)")
                        .HasColumnName("KickStudentEventId");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("DeletedAtUtc");

                    b.Property<string>("KickReason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("KickReason");

                    b.Property<DateTime>("KickedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("KickedAtUtc");

                    b.Property<string>("MentorId")
                        .IsRequired()
                        .HasColumnType("varchar(16)")
                        .HasColumnName("MentorId");

                    b.Property<string>("SeasonId")
                        .IsRequired()
                        .HasColumnType("varchar(16)")
                        .HasColumnName("SeasonId");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("varchar(16)")
                        .HasColumnName("StudentId");

                    b.HasKey("KickStudentEventId");

                    b.HasIndex("KickedAtUtc");

                    b.HasIndex("MentorId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SeasonId", "KickedAtUtc");

                    b.HasIndex("StudentId", "KickedAtUtc");

                    b.ToTable("KickStudentEvent", (string)null);
                });

            modelBuilder.Entity("RSPWebAPI.Entities.LeetcodeMockInterviewRoundEntity", b =>
                {
                    b.Property<string>("LeetcodeMockInterviewRoundId")
                        .HasColumnType("varchar(16)")
                        .HasColumnName("LeetcodeMockInterviewRoundId");

                    b.Property<int>("AlgorithmDesignScore")
                        .HasColumnType("int")
                        .HasColumnName("AlgorithmDesignScore");

                    b.Property<int>("CodingScore")
                        .HasColumnType("int")
                        .HasColumnName("CodingScore");

                    b.Property<int>("ComplexityAnalysisScore")
                        .HasColumnType("int")
                        .HasColumnName("ComplexityAnalysisScore");

                    b.Property<int>("ConfirmQuestionScore")
                        .HasColumnType("int")
                        .HasColumnName("ConfirmQuestionScore");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("DeletedAtUtc");

                    b.Property<string>("LeetcodeProblemId")
                        .IsRequired()
                        .HasColumnType("varchar(16)")
                        .HasColumnName("LeetcodeProblemId");

                    b.Property<int>("TestingScore")
                        .HasColumnType("int")
                        .HasColumnName("TestingScore");

                    b.HasKey("LeetcodeMockInterviewRoundId");

                    b.HasIndex("LeetcodeProblemId");

                    b.ToTable("LeetcodeMockInterviewRound", (string)null);
                });

            modelBuilder.Entity("RSPWebAPI.Entities.LeetcodeProblemCategoryEntity", b =>
                {
                    b.Property<string>("LeetcodeProblemCategoryId")
                        .HasColumnType("varchar(16)")
                        .HasColumnName("LeetcodeProblemCategoryId");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("DeletedAtUtc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Name");

                    b.HasKey("LeetcodeProblemCategoryId");

                    b.ToTable("LeetcodeProblemCategory", (string)null);
                });

            modelBuilder.Entity("RSPWebAPI.Entities.LeetcodeProblemEntity", b =>
                {
                    b.Property<string>("LeetcodeProblemId")
                        .HasColumnType("varchar(16)")
                        .HasColumnName("LeetcodeProblemId");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("DeletedAtUtc");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("boolean")
                        .HasColumnName("IsPremium");

                    b.Property<int>("LeetcodeNumber")
                        .HasColumnType("int")
                        .HasColumnName("LeetcodeNumber");

                    b.Property<int>("LeetcodeProblemDifficulty")
                        .HasColumnType("int")
                        .HasColumnName("LeetcodeProblemDifficulty");

                    b.Property<string>("ProblemId")
                        .IsRequired()
                        .HasColumnType("varchar(16)")
                        .HasColumnName("ProblemId");

                    b.HasKey("LeetcodeProblemId");

                    b.HasIndex("ProblemId");

                    b.ToTable("LeetcodeProblem", (string)null);
                });

            modelBuilder.Entity("RSPWebAPI.Entities.LeetcodeProblemRecommendationEntity", b =>
                {
                    b.Property<string>("LeetcodeProblemRecommendationId")
                        .HasColumnType("varchar(16)")
                        .HasColumnName("LeetcodeProblemRecommendationId");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("DeletedAtUtc");

                    b.Property<string>("LeetcodeProblemId")
                        .IsRequired()
                        .HasColumnType("varchar(16)")
                        .HasColumnName("LeetcodeProblemId");

                    b.Property<string>("ProblemAttemptId")
                        .HasColumnType("varchar(16)")
                        .HasColumnName("ProblemAttemptId");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(16)")
                        .HasColumnName("UserId");

                    b.HasKey("LeetcodeProblemRecommendationId");

                    b.HasIndex("LeetcodeProblemId");

                    b.HasIndex("ProblemAttemptId");

                    b.HasIndex("UserId");

                    b.ToTable("LeetcodeProblemRecommendation", (string)null);
                });

            modelBuilder.Entity("RSPWebAPI.Entities.MentorshipEntity", b =>
                {
                    b.Property<string>("MentorshipId")
                        .HasColumnType("varchar(16)")
                        .HasColumnName("MentorshipId");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("DeletedAtUtc");

                    b.Property<string>("MenteeEnrollmentId")
                        .IsRequired()
                        .HasColumnType("varchar(16)")
                        .HasColumnName("MenteeEnrollmentId");

                    b.Property<string>("MentorEnrollmentId")
                        .IsRequired()
                        .HasColumnType("varchar(16)")
                        .HasColumnName("MentorEnrollmentId");

                    b.HasKey("MentorshipId");

                    b.HasIndex("MenteeEnrollmentId");

                    b.HasIndex("MentorEnrollmentId");

                    b.ToTable("Mentorship", (string)null);
                });

            modelBuilder.Entity("RSPWebAPI.Entities.MockInterviewEntity", b =>
                {
                    b.Property<string>("MockInterviewId")
                        .HasColumnType("varchar(16)")
                        .HasColumnName("MockInterviewId");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("DeletedAtUtc");

                    b.Property<string>("IntervieweeUserId")
                        .IsRequired()
                        .HasColumnType("varchar(16)")
                        .HasColumnName("IntervieweeUserId");

                    b.Property<string>("InterviewerUserId")
                        .IsRequired()
                        .HasColumnType("varchar(16)")
                        .HasColumnName("InterviewerUserId");

                    b.Property<bool>("IsPass")
                        .HasColumnType("boolean")
                        .HasColumnName("IsPass");

                    b.Property<string>("Notes")
                        .HasColumnType("varchar(10000)")
                        .HasColumnName("Notes");

                    b.Property<string>("SeasonId")
                        .HasColumnType("varchar(16)")
                        .HasColumnName("SeasonId");

                    b.Property<string>("SeasonWeekId")
                        .HasColumnType("varchar(16)")
                        .HasColumnName("SeasonWeekId");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("StartDate");

                    b.Property<int>("TimeTakenInMinutes")
                        .HasColumnType("int")
                        .HasColumnName("TimeTakenInMinutes");

                    b.HasKey("MockInterviewId");

                    b.HasIndex("IntervieweeUserId");

                    b.HasIndex("InterviewerUserId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("SeasonWeekId");

                    b.ToTable("MockInterview", (string)null);
                });

            modelBuilder.Entity("RSPWebAPI.Entities.MockInterviewRoundEntity", b =>
                {
                    b.Property<string>("MockInterviewRoundId")
                        .HasColumnType("varchar(16)")
                        .HasColumnName("MockInterviewRoundId");

                    b.Property<string>("BehaviouralMockInterviewRoundId")
                        .HasColumnType("varchar(16)")
                        .HasColumnName("BehaviouralMockInterviewRoundId");

                    b.Property<string>("CustomMockInterviewRoundId")
                        .HasColumnType("varchar(16)")
                        .HasColumnName("CustomMockInterviewRoundId");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("DeletedAtUtc");

                    b.Property<string>("IntervieweeComment")
                        .IsRequired()
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("IntervieweeComment");

                    b.Property<bool>("IsReviewedByInterviewee")
                        .HasColumnType("boolean")
                        .HasColumnName("IsReviewedByInterviewee");

                    b.Property<string>("LeetcodeMockInterviewRoundId")
                        .HasColumnType("varchar(16)")
                        .HasColumnName("LeetcodeMockInterviewRoundId");

                    b.Property<string>("MockInterviewId")
                        .IsRequired()
                        .HasColumnType("varchar(16)")
                        .HasColumnName("MockInterviewId");

                    b.HasKey("MockInterviewRoundId");

                    b.HasIndex("BehaviouralMockInterviewRoundId")
                        .IsUnique();

                    b.HasIndex("CustomMockInterviewRoundId")
                        .IsUnique();

                    b.HasIndex("LeetcodeMockInterviewRoundId")
                        .IsUnique();

                    b.HasIndex("MockInterviewId");

                    b.ToTable("MockInterviewRound", (string)null);
                });

            modelBuilder.Entity("RSPWebAPI.Entities.ProblemAttemptEntity", b =>
                {
                    b.Property<string>("ProblemAttemptId")
                        .HasColumnType("varchar(16)")
                        .HasColumnName("ProblemAttemptId");

                    b.Property<DateTime>("AttemptStartDateUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("AttemptStartDateUtc");

                    b.Property<string>("CustomProblemId")
                        .HasColumnType("varchar(16)")
                        .HasColumnName("CustomProblemId");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("DeletedAtUtc");

                    b.Property<string>("EnrollmentId")
                        .HasColumnType("varchar(16)")
                        .HasColumnName("EnrollmentId");

                    b.Property<string>("LeetcodeProblemId")
                        .HasColumnType("varchar(16)")
                        .HasColumnName("LeetcodeProblemId");

                    b.Property<string>("Notes")
                        .HasColumnType("varchar(10000)")
                        .HasColumnName("Notes");

                    b.Property<string>("SeasonWeekId")
                        .HasColumnType("varchar(16)")
                        .HasColumnName("SeasonWeekId");

                    b.Property<int>("TimeTakenInMinutes")
                        .HasColumnType("int")
                        .HasColumnName("TimeTakenInMinutes");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(16)")
                        .HasColumnName("UserId");

                    b.HasKey("ProblemAttemptId");

                    b.HasIndex("CustomProblemId");

                    b.HasIndex("EnrollmentId");

                    b.HasIndex("LeetcodeProblemId");

                    b.HasIndex("SeasonWeekId");

                    b.HasIndex("UserId");

                    b.ToTable("ProblemAttempt", (string)null);
                });

            modelBuilder.Entity("RSPWebAPI.Entities.ProblemEntity", b =>
                {
                    b.Property<string>("ProblemId")
                        .HasColumnType("varchar(16)")
                        .HasColumnName("ProblemId");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("DeletedAtUtc");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("varchar(510)")
                        .HasColumnName("Link");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Title");

                    b.HasKey("ProblemId");

                    b.ToTable("Problem", (string)null);
                });

            modelBuilder.Entity("RSPWebAPI.Entities.SeasonEntity", b =>
                {
                    b.Property<string>("SeasonId")
                        .HasColumnType("varchar(16)")
                        .HasColumnName("SeasonId");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("DeletedAtUtc");

                    b.Property<DateTime>("EndDateInclusiveUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("EndDateInclusiveUTC");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ImageUrl");

                    b.Property<bool>("IsDataBackFilled")
                        .HasColumnType("boolean")
                        .HasColumnName("IsDataBackFilled");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Name");

                    b.Property<string>("ResourcesUrl")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ResourcesUrl");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("varchar(16)")
                        .HasColumnName("Slug");

                    b.Property<DateTime>("StartDateInclusiveUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("StartDateInclusiveUTC");

                    b.HasKey("SeasonId");

                    b.HasIndex("Slug");

                    b.ToTable("Season", (string)null);
                });

            modelBuilder.Entity("RSPWebAPI.Entities.SeasonWeekEntity", b =>
                {
                    b.Property<string>("SeasonWeekId")
                        .HasColumnType("varchar(16)")
                        .HasColumnName("SeasonWeekId");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("DeletedAtUtc");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("EndDate");

                    b.Property<string>("SeasonId")
                        .IsRequired()
                        .HasColumnType("varchar(16)")
                        .HasColumnName("SeasonId");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("StartDate");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("integer")
                        .HasColumnName("WeekNumber");

                    b.HasKey("SeasonWeekId");

                    b.HasIndex("SeasonId");

                    b.ToTable("SeasonWeek", (string)null);
                });

            modelBuilder.Entity("RSPWebAPI.Entities.UserEntity", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(16)")
                        .HasColumnName("UserId");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("DeletedAtUtc");

                    b.Property<string>("DiscordId")
                        .HasColumnType("varchar(16)")
                        .HasColumnName("DiscordId");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Email");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("IsAdmin");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Name");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ProfileImage");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Slug");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("LeetcodeProblemCategoryEntityLeetcodeProblemEntity", b =>
                {
                    b.HasOne("RSPWebAPI.Entities.LeetcodeProblemCategoryEntity", null)
                        .WithMany()
                        .HasForeignKey("LeetcodeProblemCategoriesLeetcodeProblemCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RSPWebAPI.Entities.LeetcodeProblemEntity", null)
                        .WithMany()
                        .HasForeignKey("LeetcodeProblemEntityLeetcodeProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RSPWebAPI.Entities.CustomProblemEntity", b =>
                {
                    b.HasOne("RSPWebAPI.Entities.ProblemEntity", "Problem")
                        .WithOne()
                        .HasForeignKey("RSPWebAPI.Entities.CustomProblemEntity", "ProblemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("RSPWebAPI.Entities.EnrollmentEntity", b =>
                {
                    b.HasOne("RSPWebAPI.Entities.SeasonEntity", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RSPWebAPI.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Season");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RSPWebAPI.Entities.KickStudentEventEntity", b =>
                {
                    b.HasOne("RSPWebAPI.Entities.UserEntity", "Mentor")
                        .WithMany()
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RSPWebAPI.Entities.SeasonEntity", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RSPWebAPI.Entities.UserEntity", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mentor");

                    b.Navigation("Season");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("RSPWebAPI.Entities.LeetcodeMockInterviewRoundEntity", b =>
                {
                    b.HasOne("RSPWebAPI.Entities.LeetcodeProblemEntity", "LeetcodeProblem")
                        .WithMany()
                        .HasForeignKey("LeetcodeProblemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LeetcodeProblem");
                });

            modelBuilder.Entity("RSPWebAPI.Entities.LeetcodeProblemEntity", b =>
                {
                    b.HasOne("RSPWebAPI.Entities.ProblemEntity", "Problem")
                        .WithMany()
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("RSPWebAPI.Entities.LeetcodeProblemRecommendationEntity", b =>
                {
                    b.HasOne("RSPWebAPI.Entities.LeetcodeProblemEntity", "LeetcodeProblem")
                        .WithMany()
                        .HasForeignKey("LeetcodeProblemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RSPWebAPI.Entities.ProblemAttemptEntity", "ProblemAttempt")
                        .WithMany()
                        .HasForeignKey("ProblemAttemptId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RSPWebAPI.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LeetcodeProblem");

                    b.Navigation("ProblemAttempt");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RSPWebAPI.Entities.MentorshipEntity", b =>
                {
                    b.HasOne("RSPWebAPI.Entities.EnrollmentEntity", "MenteeEnrollment")
                        .WithMany()
                        .HasForeignKey("MenteeEnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RSPWebAPI.Entities.EnrollmentEntity", "MentorEnrollment")
                        .WithMany()
                        .HasForeignKey("MentorEnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenteeEnrollment");

                    b.Navigation("MentorEnrollment");
                });

            modelBuilder.Entity("RSPWebAPI.Entities.MockInterviewEntity", b =>
                {
                    b.HasOne("RSPWebAPI.Entities.UserEntity", "Interviewee")
                        .WithMany()
                        .HasForeignKey("IntervieweeUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RSPWebAPI.Entities.UserEntity", "Interviewer")
                        .WithMany()
                        .HasForeignKey("InterviewerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RSPWebAPI.Entities.SeasonEntity", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RSPWebAPI.Entities.SeasonWeekEntity", "SeasonWeek")
                        .WithMany()
                        .HasForeignKey("SeasonWeekId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Interviewee");

                    b.Navigation("Interviewer");

                    b.Navigation("Season");

                    b.Navigation("SeasonWeek");
                });

            modelBuilder.Entity("RSPWebAPI.Entities.MockInterviewRoundEntity", b =>
                {
                    b.HasOne("RSPWebAPI.Entities.BehaviouralMockInterviewRoundEntity", "BehaviouralMockInterviewRound")
                        .WithOne()
                        .HasForeignKey("RSPWebAPI.Entities.MockInterviewRoundEntity", "BehaviouralMockInterviewRoundId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RSPWebAPI.Entities.CustomMockInterviewRoundEntity", "CustomMockInterviewRound")
                        .WithOne()
                        .HasForeignKey("RSPWebAPI.Entities.MockInterviewRoundEntity", "CustomMockInterviewRoundId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RSPWebAPI.Entities.LeetcodeMockInterviewRoundEntity", "LeetcodeMockInterviewRound")
                        .WithOne()
                        .HasForeignKey("RSPWebAPI.Entities.MockInterviewRoundEntity", "LeetcodeMockInterviewRoundId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RSPWebAPI.Entities.MockInterviewEntity", "MockInterview")
                        .WithMany("MockInterviewRounds")
                        .HasForeignKey("MockInterviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BehaviouralMockInterviewRound");

                    b.Navigation("CustomMockInterviewRound");

                    b.Navigation("LeetcodeMockInterviewRound");

                    b.Navigation("MockInterview");
                });

            modelBuilder.Entity("RSPWebAPI.Entities.ProblemAttemptEntity", b =>
                {
                    b.HasOne("RSPWebAPI.Entities.CustomProblemEntity", "CustomProblem")
                        .WithMany()
                        .HasForeignKey("CustomProblemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RSPWebAPI.Entities.EnrollmentEntity", "Enrollment")
                        .WithMany()
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RSPWebAPI.Entities.LeetcodeProblemEntity", "LeetcodeProblem")
                        .WithMany()
                        .HasForeignKey("LeetcodeProblemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RSPWebAPI.Entities.SeasonWeekEntity", "SeasonWeek")
                        .WithMany()
                        .HasForeignKey("SeasonWeekId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RSPWebAPI.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CustomProblem");

                    b.Navigation("Enrollment");

                    b.Navigation("LeetcodeProblem");

                    b.Navigation("SeasonWeek");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RSPWebAPI.Entities.SeasonWeekEntity", b =>
                {
                    b.HasOne("RSPWebAPI.Entities.SeasonEntity", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("RSPWebAPI.Entities.MockInterviewEntity", b =>
                {
                    b.Navigation("MockInterviewRounds");
                });
#pragma warning restore 612, 618
        }
    }
}
